object Versions {
    const val KOTLIN = "1.4.31"
    const val APPCOMPAT = "1.2.0"
    const val MATERIAL = "1.3.0"
    const val COROUTINES = "1.4.3"
    const val ROOM = "2.2.5"
    const val DATA_STORE = "1.0.0-alpha05"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.3.4"
    const val LIFECYCLE = "2.3.0"
    const val CORE_KTX = "1.5.0-alpha02"
    const val FRAGMENT_KTX = "1.3.0"
    const val CONSTRAIN_LAYOUT = "2.0.4"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val PAGING = "3.0.0-alpha07"
    const val DAGGER = "2.33"
    const val DAGGER_HILT = "2.32-alpha"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.9.1"
    const val MOSHI = "1.11.0"
    const val COIL = "0.13.0"
    const val PLAY_CORE = "1.8.2"
    const val LEAKCANARY = "2.6"
    const val DATABINDING = "3.1.4"
    const val COLLECTION_KTX = "1.1.0"
    const val MULTIDEX = "2.0.1"
    const val CHUCKER = "3.4.0"
    const val DETEKT = "1.16.0"
    const val VERSIONS_PLUGIN = "0.38.0"
    const val OK2CURL = "0.7.0"
    const val RXJAVA3 = "3.0.11"
    const val RXANDROID = "3.0.0"
    const val CIRCULAR_IMAGEVIEW = "3.1.0"

    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.2"
    const val ROBOELECTRIC = "4.4"
    const val MOCKK = "1.10.2"
    const val ASSERTJ = "3.17.2"
    const val ESPRESSO = "3.3.0"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.9.0"
}
